name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  prereq:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools twine

  build-and-publish:
    runs-on: ubuntu-latest
    needs: prereq
    steps:
      - name: Build
        run: |
          python setup.py sdist bdist_wheel
        
      - name: Publish
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          twine upload dist/*
      
